// TODO: #![deny(missing_docs)]
#![warn(clippy::pedantic)]

mod access;
#[macro_use]
mod partial;

#[cfg(test)]
mod tests {
    #![allow(dead_code)]

    use crate::access::Access;
    use std::marker::PhantomData;

    partial! {person {
        name: String,
        age: u8,
    }}

    // All fields are required by default
    impl person::Struct {
        fn say_hello(&self) -> String {
            format!("Hi! I'm {} and I'm {} years old", self.name, self.age)
        }
    }

    // Any person that has at least a name
    impl<T: person::has::name> Named for T {}
    trait Named: person::has::name {
        fn shout_name(&self) -> String {
            // this borrows Self as Person, so that the fields can be accessed
            let borrowed = self.borrow();
            let uppercase = borrowed.name.to_uppercase();
            match borrowed.age.get() {
                Some(age) => format!("{uppercase} ({age})"),
                None => uppercase,
            }
        }
    }

    #[test]
    fn example() {
        // we don't know John's age yet
        let john = person::Struct {
            name: "John".to_string(),
            age: PhantomData,
        };

        // we can call shout_name, but not say_hello
        assert_eq!(john.shout_name(), "JOHN");

        let p = person::Struct {
            age: 26,
            name: john.name,
        };

        // now that we know John's age, we can call say_hello
        assert_eq!(p.say_hello(), "Hi! I'm John and I'm 26 years old");

        // the behaviour of shout_name changes since john has an age
        assert_eq!(p.shout_name(), "JOHN (26)");
    }

    // This will be generated by a future version of the partial! macro
    mod with {
        #![allow(non_camel_case_types)]
        #![allow(type_alias_bounds)]

        pub type age<T: super::person::Interface> = super::person::Struct<T::name, u8>;
    }

    fn with_age<T: person::Interface>(person: T, age: u8) -> with::age<T> {
        person::Struct {
            age,
            name: person.into().name,
        }
    }
}
